### ISSUE TITLE
Legacy warning

### ISSUE THREAD

**Issue by newrokor** [oGGy990/certbot-dns-inwx#16]
Hi oGGy990,

`certbot renew --dry-run` works fine, however, I get a legacy warning:

`
... Cert not due for renewal, but simulating renewal for dry run
Plugin legacy name certbot-dns-inwx:dns-inwx may be removed in a future version. Please use dns-inwx instead.
Plugins selected: Authenticator certbot-dns-inwx:dns-inwx, Installer None ...
`

Is there a software update necessary, or do I have to redo the `certbot certonly (--dry-run) --authenticator certbot-dns-inwx:dns-inwx --cert-name ... -d ...` stuff? Thanks in advance.

newrokor

**Comment by oGGy990** [comment]
Hi newrokor,

thanks for notifying me. You are right, since [certbot 1.7.0](https://github.com/certbot/certbot/blob/master/certbot/CHANGELOG.md#170---2020-08-04) those ugly prefixes are not required anymore.

This only concerns the `README.md` and the `inwx.cfg` file. Just strip the `certbot-dns-inwx:` prefix from all command line arguments and the configuration file and you should be good to go.

If you have already setup any certificates using the authenticator, you may need to update your renewal files (`/etc/letsencrypt/renewal`) and also strip the prefixes there to be on the safe side once they remove support for those previously required prefixes completely.

I will update the repository accordingly and push a new version to PyPi next week.

**Comment by newrokor** [comment]
Thanks for the prompt reply. That was the main intetion to point you to the legacy stuff.

I tried it now with inwx.cfg AND the renewal files (forgot these in the first try) changed, and the dry run is fine.

newrokor

**Comment by oGGy990** [comment]
I have changed the README and inwx.cfg with commit 9e86612 .

But I'll delay a new version, because I want to remove the PPA and certbot-auto instructions and instead provide a snap containing the plugin. certbot-auto is deprecated and the EFF recommends to install the snap everywhere.

One can hack the plugin into the snap installation of certbot by doing a user installation via pip but that is ugly. So I'll try to use the certbot snap plugin interface. Won't happen before next week though.

**Comment by jdoubleu** [comment]
Any updates on the progress for a snap?

Certbot [provides a script](https://certbot.eff.org/docs/contributing.html#writing-your-own-plugin-snap) to create snaps for dns plugins. As far as I understood, you don't have to put anything else but the actual plugin script into the snap, because certbot will prefer the python binary and packages from its snap.

**Comment by oGGy990** [comment]
Hey there,
took a while but I finally found the time to setup a VM for snap development.
You may now install the plugin via snap! Instructions are within the updated README.

Closing this. :-)
