### ISSUE TITLE
Missing properties in credentials configuration file /etc/letsencrypt/inwx.cfg:

### ISSUE THREAD

**Issue by TobiasCurth** [oGGy990/certbot-dns-inwx#17]
Hi,

thank you, for your helpful script! 

After installing and configuring like mentioned here https://github.com/oGGy990/certbot-dns-inwx/blob/master/inwx.cfg I ran into following error: 

Missing properties in credentials configuration file /etc/letsencrypt/inwx.cfg:
 * Property "certbot_dns_inwx:dns_inwx_url" not found (should be URL of the INWX XML-RPC API to use.).
 * Property "certbot_dns_inwx:dns_inwx_username" not found (should be Username of the INWX API account.).
 * Property "certbot_dns_inwx:dns_inwx_password" not found (should be Password of the INWX API account.).
 * Property "certbot_dns_inwx:dns_inwx_shared_secret" not found (should be Optional shared secret code for the two-factor authentication assigned to the INWX API account.).

Solution:
In inwx.cfg there must be the parameters like "certbot_dns_inwx:dns_inwx_url" instead of "dns_inwx_url".

You should fix this in your documentation/sample file. 

Thanks!

**Comment by oGGy990** [comment]
Hi Tobias,

thanks for taking the time to open the ticket!

Those names have changed since certbot 1.7.0. See also https://github.com/oGGy990/certbot-dns-inwx/issues/16#issuecomment-719059322. You are likely using an older version of certbot.

This is why I've added the following remark to the README: https://github.com/oGGy990/certbot-dns-inwx#usage-on-certbot--v170 which also linked right below the documentation concerning the configuration file.

I'll close this ticket for the time being, but feel free to reopen it if you are using certbot >=1.7.0. :-)
